import matplotlib.pyplot as plt

import pandas as pd
plt.style.use('dark_background')
df = pd.read_csv("sales_dataset_120_rows.csv")
print(df)

print(df.columns)

import numpy as np

# Create a line chart showing daily revenue over time

# plt.plot(df['Date'],df['Revenue'], color = 'Red')
# plt.xlabel('Date')
# plt.ylabel('revenue')
# plt.title("daily revenue graph")
# plt.show()

df.drop_duplicates(subset='Product')
# Plot total revenue generated by each product using a bar chart.

# plt.bar(df['Product'] , df['Revenue'] , color = 'white' , edgecolor='green',facecolor = 'WHITE')
# plt.xlabel('Product')
# plt.ylabel('Revenue')
# plt.title("Product V Revenue")
# plt.show()

# total = df.groupby('Region')['Units_Sold'].sum()
# plt.bar(total.index,total.values)
# plt.xlabel('Total')
# plt.ylabel('region')
# plt.show()



# Create a pie chart showing percentage contribution of each product to total revenue
# t = df.groupby('Product')['Revenue'].sum()
# plt.pie(
#     t.values,
#     labels=t.index,
#     autopct='%1.1f%%',
#     startangle=90

# )
# plt.show()


# Create a histogram for Units_Sold.


# plt.hist(df['Units_Sold'] , bins = 10 , edgecolor = 'red')
# plt.show()

# month = df.groupby()

# Plot monthly revenue trend using a line chart with markers

df['Date'] = pd.to_datetime(df['Date'])

month = df.groupby(df['Date'].dt.month_name())['Revenue'].sum()

# plt.plot(month.index , month.values,color = 'green' , marker = 'o' , linestyle = '--', linewidth = 2)
# plt.xlabel('month')

# plt.ylabel('revenue')
# plt.title("Monthly revenue")

# plt.show()


# □ Q7

# Create a scatter plot of:

# X = Units Sold
# Y = Revenue\
# x = df['Units_Sold']
# y = df['Revenue']
# plt.scatter(x,y,color = 'STEELBLUE' , marker='o' , s=30)
# plt.xlabel('Unit_sold')
# plt.ylabel('Revenue')
# plt.title('UNIT)SOLD V REVENUE')

# plt.show()
reg = df.groupby('Region')['Revenue'].mean()
# plt.plot(reg.index , reg.values , color = 'red')
# plt.xlabel('region')
# plt.ylabel('revenue')
# plt.show()


# boc = [group['Revenue'] for _, group in df.groupby('Product')]

# plt.boxplot(boc,label='product')
# plt.title('revenue distribution')
# plt.show()



# □ Q11

# Create a figure containing:

# Revenue by Product
# Revenue by Region

# # using two subplots.

# fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

# ax1.bar(prod.index, prod.values)
# ax1.set_title('Revenue by Product')

# reg = df.groupby('Region')['Revenue'].sum()
# ax2.bar(reg.index, reg.values)
# ax2.set_title('Revenue by Region')

# plt.tight_layout()
# plt.show()


# Create a dashboard containing:

# Revenue Trend
# Units Sold Trend
# Product Revenue
# Region Revenue

# using four subplots.

fig, axes = plt.subplots(2, 2, figsize=(10, 5))

ax1 = axes[0, 0]
ax2 = axes[0, 1]
ax3 = axes[1, 0]
ax4 = axes[1, 1]

ax1.plot(df['Date'],df['Revenue'] , color = 'RED' , linestyle ='--' , linewidth = 2)
ax1.set_title('Revneue Trend')
ax1.tick_params(axis='x', rotation=45)


up = df.groupby('Product')['Units_Sold'].sum()

ax2.plot(up.index , up.values , color = 'green')
ax2.set_title("unit sold Trend")


prod = df.groupby('Product')['Revenue'].sum()

ax3.bar(prod.index , prod.values , color = 'white')
ax3.set_title("Product Revenue")

reg = df.groupby('Region')['Revenue'].sum()

ax4.bar(reg.index , reg.values,color = 'Yellow')
ax4.set_title("Region Revenue")



plt.tight_layout()
plt.show()





